
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int Or = 34;
  public static final int True = 18;
  public static final int cls = 22;
  public static final int doubleequalto = 36;
  public static final int If = 3;
  public static final int comments = 20;
  public static final int Floatlit = 13;
  public static final int Void = 37;
  public static final int closesquare = 43;
  public static final int charlit = 9;
  public static final int INT = 14;
  public static final int greaterthanequalto = 26;
  public static final int Else = 8;
  public static final int comma = 47;
  public static final int negate = 39;
  public static final int greaterthan = 27;
  public static final int opencurly = 44;
  public static final int questions = 48;
  public static final int INTLIT = 12;
  public static final int lessthanequalto = 25;
  public static final int lessthan = 28;
  public static final int decre = 24;
  public static final int Return = 7;
  public static final int Final = 38;
  public static final int While = 4;
  public static final int Float = 16;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int Not = 35;
  public static final int Printline = 6;
  public static final int And = 33;
  public static final int error = 1;
  public static final int closeround = 41;
  public static final int False = 19;
  public static final int colon = 49;
  public static final int Char = 15;
  public static final int Print = 5;
  public static final int Subtract = 30;
  public static final int multiple_comments = 21;
  public static final int incre = 23;
  public static final int READ = 11;
  public static final int Add = 29;
  public static final int equalto = 50;
  public static final int open_round = 40;
  public static final int Bool = 17;
  public static final int closecurly = 45;
  public static final int opensquare = 42;
  public static final int Strlit = 10;
  public static final int Divide = 32;
  public static final int Multiply = 31;
  public static final int semicolon = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "If",
  "While",
  "Print",
  "Printline",
  "Return",
  "Else",
  "charlit",
  "Strlit",
  "READ",
  "INTLIT",
  "Floatlit",
  "INT",
  "Char",
  "Float",
  "Bool",
  "True",
  "False",
  "comments",
  "multiple_comments",
  "cls",
  "incre",
  "decre",
  "lessthanequalto",
  "greaterthanequalto",
  "greaterthan",
  "lessthan",
  "Add",
  "Subtract",
  "Multiply",
  "Divide",
  "And",
  "Or",
  "Not",
  "doubleequalto",
  "Void",
  "Final",
  "negate",
  "open_round",
  "closeround",
  "opensquare",
  "closesquare",
  "opencurly",
  "closecurly",
  "semicolon",
  "comma",
  "questions",
  "colon",
  "equalto"
  };
}

